apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: three-tier
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'kubernetes-backend'
        metrics_path: /metrics
        static_configs:
          - targets: ['backend-service.three-tier.svc.cluster.local:3000']
            labels:
              job: backend
